language: php

branches:
  only:
    - master
    - 4.0

services:
  - mysql
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - nightly

env:
  - DB_USER=travis FTP_USER=bob FTP_PASSWORD=12345

before_install:
  - docker run --net=host -p 21:21 -e USER=$FTP_USER -e PASS=$FTP_PASSWORD -d --name proftpd -v $(pwd)/:/ftp/$FTP_USER emilybache/vsftpd-server
install:
  - composer install --prefer-dist

before_script:
  - ./vendor/bin/phpcs --standard=psr2 --severity=4 --tab-width=4 src --ignore="tests"
  - if [ ! -d ./tests/data/cache ]; then mkdir -p ./tests/data/cache; fi;
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - ./vendor/bin/phpunit --configuration phpunit.dist.xml

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
