language: php

branches:
  only:
    - master

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - nightly

env:
  - DB_USER=travis

before_script:
  - ./vendor/bin/phpcs --standard=psr2 --severity=4 --tab-width=4 src --ignore="tests"
  - if [ ! -d ./tests/data/cache ]; then mkdir -p ./tests/data/cache; fi;
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

script:
  - ./vendor/bin/phpunit --configuration phpunit.dist.xml
