name: Bow Framework CI

on:
  push:
    branches: 
      - 4.0
      - master
  pull_request:
    branches: 
      - 4.0
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - run: docker run --net=host -p 21:21 -e USER=$FTP_USER -e PASS=$FTP_PASSWORD -d --name ftp -v $(pwd)/:/ftp/$FTP_USER emilybache/vsftpd-server
      - run: docker run -p 1025:25 -p 1080:80 -d --name maildev maildev/maildev
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Create test cache directory
        run: if [ ! -d ./tests/data/cache ]; then mkdir -p ./tests/data/cache; fi;
      - name: Check code standard
        run: ./vendor/bin/phpcs --standard=psr2 --severity=4 --tab-width=4 src --ignore="tests"
      - name: Run test suite
        run: composer run-script test
